### ISSUE TITLE
Is there a reason to run API version recognition upon require

### ISSUE THREAD

**Issue by mensfeld** [thedrummeraki/mangadex#2]
Hey,

I'm talking about this line: https://github.com/thedrummeraki/mangadex/blob/culture/lib/mangadex/api/version.rb#L21

It makes a request to mangadex API the moment the package is required. What that means is, when working offline (say in an airplane) or doing any type of pre-building, rake tasks, etc it triggers call to Mangadex.

This can have impact not only on the code but also on the mangadex API in terms of number of requests "for nothing".

**Comment by thedrummeraki** [comment]
@mensfeld Thanks for reaching out. To be honest, I don't _really_ think it's necessary to have that here. I'll just probably remove the constant and move that logic to a method.

**Comment by thedrummeraki** [comment]
Potential fix: https://github.com/thedrummeraki/mangadex/pull/3

I'll have another look tomorrow after work.

**Comment by mensfeld** [comment]
Looks much better! :)
