### ISSUE TITLE
Keyword Arguments Issue

### ISSUE THREAD

**Issue by royalgiant** [thedrummeraki/mangadex#52]
@thedrummeraki 
Trying to understand for the life of me how to make this conditional...

```
args = {
      limit: @limit,
      offset: @current_offset,
      available_translated_language: ['en', 'uk'],
      includes: [:cover_art, :author, :artist]
}
args[:title] = params[:search].to_s if params[:search].present?
args[:included_tags] = [params[:tag].to_s] if params[:tag].present?
@mangas = Mangadex::Manga.list(args)
```
 ,

I'm trying to include the `title` and `included_tags` args only if they exist (user has inputted). But if you run that above code, you'll get 

`ArgumentError (wrong number of arguments (given 1, expected 0)):`

<img width="1280" alt="Screen Shot 2022-11-05 at 4 42 43 PM" src="https://user-images.githubusercontent.com/845626/200140564-9bf55544-e8d0-42b2-bbb8-f5e79866d760.png">

Not too familiar with the keyword args here. How do I do this correctly?

Thanks,
Donald

https://github.com/thedrummeraki/mangadex/blob/24b27843b8e10e8b8a6490aafbecb4f452b81dae/lib/mangadex/manga.rb#L29

**Comment by thedrummeraki** [comment]
Hey @royalgiant, thanks for the question! have you tried

```
@mangas = Mangadex::Manga.list(**args)
```

All methods accept `args` as keyword arguments not as a Hash.

**Comment by thedrummeraki** [comment]
Looking at your code, looks like you're passing `limit` and `offset`. I've released some patch versions that allow you to pass those as strings so you don't have to convert them to integers first. You can `bundle update mangadex` to get the latest version (`5.7.5.2`). Good luck!

**Comment by royalgiant** [comment]
Didn't quite answer my question actually, here's what I mean, currently I have:
```
@mangas = Mangadex::Manga.list(
      limit: @limit,
      offset: @current_offset,
      title: params[:search].to_s,
      included_tags: [params[:tag].to_s],
      available_translated_language: ['en', 'uk'],
      includes: [:cover_art, :author, :artist]
    )
```
If `tags` is empty, that'll blow up because we'll pass an empty string, and Mangadex will pass back an error looking for a 36 char uuid.

In order to use this I have to do something like this to take into account empty or non-empty tags and title:

```
if params[:search].present? 
      @mangas = Mangadex::Manga.list(
        limit: @limit,
        offset: @current_offset,
        title: params[:search].to_s, # Couldn't include `included_tags` key here because it is not present, Mangadex will complain of error.
        available_translated_language: ['en', 'uk'],
        includes: [:cover_art, :author, :artist]
      )
    elsif params[:tag].present? 
      @mangas = Mangadex::Manga.list(
        limit: @limit,
        offset: @current_offset,
        included_tags: [params[:tag].to_s], # I can only do this if tag is present.
        available_translated_language: ['en', 'uk'],
        includes: [:cover_art, :author, :artist]
      )
    elsif params[:search].present? && params[:tag].present?  # I have both title and tag, I can do this without Mangadex complaining.
      @mangas = Mangadex::Manga.list(
        limit: @limit,
        offset: @current_offset,
        title: params[:search].to_s, 
        included_tags: [params[:tag].to_s],
        available_translated_language: ['en', 'uk'],
        includes: [:cover_art, :author, :artist]
      )
    end
```
I'm wondering how to "Don't repeat yourself" that code.

You can't do something like conditionals in keyword arguments as far as I know
```
@mangas = Mangadex::Manga.list(
        limit: @limit,
        offset: @current_offset,
        title: params[:search].to_s, 
        params[:tag].present? ? (included_tags: [params[:tag].to_s]) : nil, # this does not work
        available_translated_language: ['en', 'uk'],
        includes: [:cover_art, :author, :artist]
      )
```
Hope that clarifies what problem I'm facing.

**Comment by royalgiant** [comment]
@thedrummeraki Nevermind, I figured it out. That was a literal rubber duck moment. 👎 

I'll go update your readme sometime this week. This problem I was wrestling with for hours. :P

**Comment by thedrummeraki** [comment]
Ohh no sorry I was referring the exception you were getting because the `args` were passed in as an argument and not keyword arguments:

```
ArgumentError (wrong number of arguments (given 1, expected 0))
```

Other than that, what you did make sense (ie: conditionally pass in `:included_tags` when present). What ended up being the problem? I'm currently working on making filters a bit easier to work with and want to make sure that I'm working could help with your problem!

**Comment by thedrummeraki** [comment]
@royalgiant Closing this issue for now, feel free to reopen if you have another question.
